// Reducer normal actions
export const ITEM_NAME = "ITEM_NAME";

// API actions
export const GET_ALL_ORDER_HISTORY_REQUEST = "GET_ALL_ORDER_HISTORY_REQUEST";
export const GET_ALL_ORDER_HISTORY_RESPONSE = "GET_ALL_ORDER_HISTORY_RESPONSE";
export const GET_ALL_ORDER_HISTORY_ERROR = "GET_ALL_ORDER_HISTORY_ERROR";

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_RESPONSE = "GET_ORDER_BY_ID_RESPONSE";
export const GET_ORDER_BY_ID_ERROR = "GET_ORDER_BY_ID_ERROR";

export const PUSH_NEW_NOTIFICATION = "PUSH_NEW_NOTIFICATION";
export const DELETE_ALL_NOTIFICATIONS = "DELETE_ALL_NOTIFICATIONS";
export const DELETE_A_NOTIFICATION = "DELETE_A_NOTIFICATION";

export const NOT_HAVE_NEW_NOTIF = "NOT_HAVE_NEW_NOTIF";
export const HAVE_NEW_NOTIF = "HAVE_NEW_NOTIF";

export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST";
export const GET_ALL_CATEGORIES_RESPONSE = "GET_ALL_CATEGORIES_RESPONSE";
export const GET_ALL_CATEGORIES_ERROR = "GET_ALL_CATEGORIES_ERROR";

export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_RESPONSE = "GET_ALL_PRODUCTS_RESPONSE";
export const GET_ALL_PRODUCTS_ERROR = "GET_ALL_PRODUCTS_ERROR";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_RESPONSE = "GET_PRODUCT_BY_ID_RESPONSE";
export const GET_PRODUCT_BY_ID_ERROR = "GET_PRODUCT_BY_ID_ERROR";
export const GET_CART = "GET_CART";
export const CHANGE_SIZE = "CHANGE_SIZE";
export const MERGE_PRODUCT = "MERGE_PRODUCT";
export const VERIFY_QUANTITY = "VERIFY_QUANTITY";
export const DELETE_PRODUCT_IN_CART = "DELETE_PRODUCT_IN_CART";
export const CHANGE_CHECK_OUT_STATUS = "CHANGE_CHECK_OUT_STATUS";
export const GET_ADD_ORDER_TO_CART_REQUEST = "GET_ADD_ORDER_TO_CART_REQUEST";
export const PAID_STATUS = "PAID_STATUS";
export const HANLDING_CHECKOUT = "HANLDING_CHECKOUT";
export const PACKED_ORDER = "PACKED_ORDER";
export const POSTED_ORDER = "POSTED_ORDER";
export const COMPLETED_CHECKOUT = "COMPLETED_CHECKOUT";
export const LOADING_ON = "LOADING_ON";
export const LOADING_OFF = "LOADING_OFF";
